// Generated by CoffeeScript 1.6.3
var target1 = document.getElementById("target1");
var target2 = document.getElementById("target2");

target1.dataset.active = false;
target1.dataset.angle = 0;

target2.dataset.active = false;
target2.dataset.angle = 0;

DragObject(target1);
springBack(target1);
DragObject(target2);
springBack(target2);

function DragObject(target) {
  var R2D, center, init, rotate, rotation, start, startAngle, stop;

  active = false;

  angle = 0;

  rotation = 0;

  startAngle = 0;

  center = {
    x: 0,
    y: 0
  };

  document.ontouchmove = function(e) {
    return e.preventDefault();
  };

  init = function() {
    target.addEventListener("mousedown", start, false);
    target.addEventListener("mousemove", rotate, false);
    return target.addEventListener("mouseup", stop, false);
  };

  R2D = 180 / Math.PI;

  start = function(e) {
    var height, left, top, width, x, y, _ref;
    e.preventDefault();
    _ref = this.getBoundingClientRect(), top = _ref.top, left = _ref.left, height = _ref.height, width = _ref.width;
    center = {
      x: left + (width / 2),
      y: top + (height / 2)
    };
    x = e.clientX - center.x;
    y = e.clientY - center.y;
    startAngle = R2D * Math.atan2(y, x);
    // targetRotation = parseInt(target.style.transform.replace(/rotate\(|deg\)/g, ""));
 	  // if (targetRotation < 0) {
 	  // 	Math.abs(targetRotation += 360);
 	  // }
 	  // startAngle = targetRotation;
    target.dataset.active = true;
    return active = true;
  };

  rotate = function(e) {
    angle = parseInt(this.dataset.angle);
    var d, x, y;
    e.preventDefault();
    x = e.clientX - center.x;
    y = e.clientY - center.y;
    d = R2D * Math.atan2(y, x);
    rotation = d - startAngle;
    if (active) {
      return this.style.webkitTransform = "rotate(" + (angle + rotation) + "deg)";
    }
  };

  stop = function() {
    angle += rotation;
    target.dataset.angle = angle;
    target.dataset.active = false;
    return active = false;
  };

  init();

}
function springBack(target) {
  var angle = parseInt(target.dataset.angle);
  if (angle < 0) {
    angle += 360
  }
  if (angle > 360) {
    angle -= 360
  }
  if (target.dataset.active == "true") {} else {
    if (angle > 0) {
      angle = Math.ceil(angle - 1)
    }
    target.style.transform = "rotate(" + angle + "deg)";
  }
  target.dataset.angle = angle;
  var springBackTimeout = setTimeout(springBack, 16, target)
}